### ISSUE TITLE
Make GitHub workflow work

### ISSUE THREAD

**Issue by Fohlen** [eventzimmer/dashboard#3]
There is a continuous integration workflow in this repository. It should check the project with `npm run lint`. However it does not work for some weird reasons. Figure out why, and (if possible), make it mandatory for pull requests to pass.

**Comment by philipmckenna** [comment]
Have you got beta access to actions? I cannot see an actions tab on your repo? Github actions is an opt-in beta at this moment with a big waitlist https://github.com/features/actions. What you currently have in your repo would do what you say on merge. To change to pull request as well just change `on: [push]` to `on: [push, pull_request]`.

**Comment by Fohlen** [comment]
Hey @philipmckenna and thanks for the input. I am whitelisted for GitHub actions, however apparently the `eventzimmer` organization is not. I wasn't aware of that, will fix it!

**Comment by Fohlen** [comment]
Hey @philipmckenna the actions are now available. I fixed this with d72d815f98ac0b62036cc159ab2f50dfbd206a2c. However you may add yourself to the [CONTRIBUTORS](https://github.com/eventzimmer/schema/blob/master/CONTRIBUTORS.md) list, as you like (e.g with a Hacktoberfest label / title, so it will be counted towards your contributions).
